[run]
init_cmds = [
	["make", "build-dev", "TAGS=sqlite"],
	["./gogs", "web"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/cmd",
	"$WORKDIR/models",
	"$WORKDIR/modules",
	"$WORKDIR/routers"
]
watch_exts = [".go"]
ignore_files = [".+_test.go"]
build_delay = 1500
cmds = [
	["make", "build-dev", "TAGS=sqlite"], # cert pam tidb
	["./gogs", "web"]
]