sudo: required

# trusty required for docker
# https://github.com/travis-ci/travis-ci/issues/5448
dist: trusty

services:
  - docker

language: go

matrix:
  include:
    - go: 1.5.3

install:
  - go get github.com/tools/godep
  - ./hack/install-etcd.sh
  - ./hack/build-go.sh
  - export PATH=$GOPATH/bin:./third_party/etcd:$PATH

script:
  - make verify BRANCH=$TRAVIS_BRANCH

notifications:
  irc: "chat.freenode.net#kubernetes-dev"
  slack: kubernetes:PHPPkljtEsHXED6xl9IfOvKe
