- job:
    name: kubernetes-test-summary
    description: 'Create a daily test summary and upload to GCS. Test owner: spxtr.'
    triggers:
        # Run every night at midnight at a random minute.
        - timed: 'H 0 * * *'
    scm:
        - git:
            url: https://www.github.com/kubernetes/kubernetes
            branches:
                - master
            browser: githubweb
            browser-url: https://github.com/kubernetes/kubernetes
            skip-tag: true
    builders:
        - shell: |
            cd hack/jenkins/test-history
            ./gen_history http://jenkins-master:8080/
    publishers:
        - email-ext:
            recipients: spxtr@google.com
