kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-gluster-worker-controller
  labels:
    component: spark-worker
spec:
  replicas: 2
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
        uses: spark-master
    spec:
      containers:
        - name: spark-worker
          image: gcr.io/google_containers/spark-worker:1.5.1_v2
          ports:
            - containerPort: 8888
          volumeMounts:
            - mountPath: /mnt/glusterfs
              name: glusterfsvol
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: glusterfsvol
          glusterfs:
            endpoints: glusterfs-cluster
            path: MyVolume
            readOnly: false
