language: go

os:
  - osx

go:
  - 1.4
  - 1.5
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

install:
  - "go get -v github.com/golang/protobuf/..."
  - "mkdir -p $GOPATH/github.com/lxc"
  - "rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/lxc/lxd/"

script:
  - "[ \"$TRAVIS_OS_NAME\" != \"osx\" ] || make client"

notifications:
  webhooks: https://linuxcontainers.org/webhook-lxcbot/
